version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    # set loglevel
    command: redis-server --loglevel verbose

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    volumes:
      - minio_data:/data
    command: server /data --address "0.0.0.0:9000"
volumes:
  minio_data:
    